name: appenv
channels:
  - conda-forge
dependencies:
  - python=3.10
  - geopandas=0.13.2 
  - branca=0.6.0
  - numpy=1.25.0
  - folium=0.14.0
  - pillow=9.4.0
  - streamlit=1.25.0 
  - streamlit_floium=0.12.0  
  - plotly=5.14.1
  - plotly_express=0.4.1